TrajectoryPlannerROS:
  max_vel_x: 0.8
  min_vel_x: 0.1
  max_vel_theta: 0.1
  min_in_place_vel_theta: 0.01

  acc_lim_theta: 1.5
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  escape_vel: -0.3

  holonomic_robot: false

  meter_scoring: true
