#plugins:
#  - {name: sonar_layer,   type: "range_sensor_layer::RangeSensorLayer"}

obstacle_range: 2.0
raytrace_range: 2.0
footprint: [[-0.08, -0.05],[-0.08, 0.05],[0.08, 0.05],[0.08, -0.05]]
#robot_radius: ir_of_robot
inflation_radius: 0.05

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
