global_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.5
  static_map: false
  transform_tolerance: 0.5
  width: 100.0
  height: 100.0
  origin_x: -50.0
  origin_y: -50.0
  resolution: 0.01
