local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 0.5
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 100.0
  height: 100.0
  origin_x: -50.0
  origin_y: -50.0
  resolution: 0.05
  transform_tolerance: 0.5
